[project]
name = "ascensores"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "gspread>=6.2.1",
    "oauth2client>=4.1.3",
    "streamlit>=1.50.0",
]
